
[app-service]
registry-dir = "/tmp/apps"

[app-service.addr]
ip = "0.0.0.0"
port = 9993

[rust-service.addr]
ip = "0.0.0.0"
port = 8000

[novatel-oem6-service]
bus = "/dev/ttyS1"

[novatel-oem6-service.addr]
ip = "0.0.0.0"
port = 8123

[clyde-3g-eps-service]
bus = "/dev/i2c-1"

[clyde-3g-eps-service.addr]
ip = "0.0.0.0"
port = 8124

[isis-ants-service.addr]
ip = "0.0.0.0"
port = 8125

[isis-ants-service]
bus = "/dev/i2c-1"
primary = "0x31"
secondary = "0x32"
antennas = 4
wd_timeout = 10
