name: Build

on: 
  push:
  pull_request:

jobs:
    fsw:
      # Container setup
      runs-on: ubuntu-latest
      container:
        image: ivvitc/nos3-64:dev
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: 'true'
        - name: Update
          run: apt-get update
        - name: Install dependencies
          run: apt-get install -y python3
        - name: prep
          run: make prep
        - name: fsw
          run: make config fsw
